// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTc8_U1P6cyJudTqlHr0DNO_G-WL8_ZQw',
    appId: '1:353854518276:android:1af4eccf5ad6e889d33151',
    messagingSenderId: '353854518276',
    projectId: 'investplay-74e02',
    storageBucket: 'investplay-74e02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkvZ_EYvDiwtSifuc0-_tal8CTtKGjTyA',
    appId: '1:353854518276:ios:62a66a7b62ed306ad33151',
    messagingSenderId: '353854518276',
    projectId: 'investplay-74e02',
    storageBucket: 'investplay-74e02.firebasestorage.app',
    iosBundleId: 'com.example.investplay',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB-2HJ2uJHnkvh3eKezGmG93I23rTDAxA',
    appId: '1:353854518276:web:0fc176e0d01704a5d33151',
    messagingSenderId: '353854518276',
    projectId: 'investplay-74e02',
    authDomain: 'investplay-74e02.firebaseapp.com',
    storageBucket: 'investplay-74e02.firebasestorage.app',
    measurementId: 'G-KLXSDR2GB0',
  );

}